---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBTGe0K6tyauR2ThAedYB7Ix91v7iweg43P+CzYbp6z/rKzOuOJbRq8NKdsEDK0JyX09Kf/lZrbkWeuh4OAX9Wh6c6TGPKGuD5NLfxRyaGx5kVYAsazX0k0x5iv3mqJZBBqF+9fWul3MHtWKFqHLC3QnSYk9uyUmMBm1fGCt7q6mnLvejfIVapK7vZqX85uUWCetsDz4YLAh6dV7TwpRJvFw31vT5GntkfB+kUIRlzZK4anRKlbgsZm2TsdE1/zzcWKYLrMun11MQ5s17i/HImyLy0pcmW4YbwG9SI8pn+7wn8zJQllsK0ExkPtSVfH0cbiBV8fxgaO7IXWyewSUYnpj7pT7KFep9rUEw/of5XKe3IaFpmaairV8UthJY8ZR3k52ZDEIWyASJwNPcs5JL0NbzTcVyYg++KtaMp+WdtP1VWdme2VF8gRkFlN/yBxlGeinxAK7YPl8/ab4DmZc10SQwQaPY+vqDhSnxu8sk1axwkPJpgLwIEOERvQOAWKXl/cMUsfT8q4s34d1HIVzYL81WZ25ERNodQC035GnGHDaE+X+byaopJ3K/MQt1eKKL/obaS1TG737wz1Z67Hjf2qMI3FRhu/1y3CHIiqY57qJn2INLcQh+9wuwtvPKgIk37qQbeYA/gMM2gDuE3fDULa7dHZmZaAo8fRM5Jgabtjj+vXx0vu+rlxNTqNeFznA9dZfdAMMHyCzRH1NTG5jGynkzbQss4a225BTjo17iqoopXPjmsiK7e8ggfGRay7rLR9KDlK5BqMEDQWTfUj3OUa1PwzVAbTtZxyzUzyvmzJ860aWREguTfkfK3p0rzQWHx9fuXpV/AZwBsIQgBycOXJb9ehU3S4GOYpdlxrTtg946thFKto6fqRbQW8XQY9lu81HnJNWLYp1GKos0sD/nRLWTx8dz3MGWuwpHJTfzESq3j6vJCCuOJdriZAvfUwg2cnjkivoY2E3r62uHYkTk+pBiNa
  template:
    metadata:
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
