---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-secret
  namespace: default
spec:
  encryptedData:
    KMA_SERVICE_KEY: AgCMcKMc8f3TQSFLqJmXkMYwgToE3VDpXseH254AkF+NJVm4jg7Q3/Zx53JJWmxEWjfZGr2PTnoYyLVToDsVAXAz5rjmCTzg7B2Br5uw4RoWkcOdXaD5vcLY5XlDAzmGK3Vf/yuqEo5LTjYw9UVOQn0zQBjGwBg/+CvAPKKBh2dSqHWU6JN8ZncqKqg4vh3PBPe7JZql0uxFoBV6dms2Mdq96jr2MHlrmxc5hiXGCSv43Hsa3ZmdcuCITZtR2saN5Pf3/tdI5mmOsLYgrZkFMwngPtu8kzuzeOulfFyV9dXGXSBZAz7z9arTSRPvAEsHfWlA0xqYOZZav3hmXxtWvRlSK5eDijDT5PL1tVns9zSSEENwEZDuByN0hBI+oj7ng8bPOyhAglkKqi5oPKsJvx5J6pf2PKbfDwM5rqwHWMDOxlJWkSC3pRiGiy0cdx+OycJbs1NhflaBzq3vcIo2skGFRg7icxyi/VVm5nMMsxpDfNtMt5HMX0EIaI86/dlJNl1jQLAGrlTpLHRghAJ0Dts68IwyerXfNu2fMbQcdYd00sE1s+nt7wnU2kCMQe2rDu1akpzkVgmahVVE715uen3T0DpCcGuoWIEl7SNggcYlCbq1yUVCCjRMfTZVDM2BGWjQtiUmKM7tXTIY527gpDJskQMPVK6OJIy/GXEsI08EzwtPLeoaBREPna0CjBwVWLGbmzs8LGFebNkXVXI+LnNvMckOfsJvMV/iR5rp31UeC0G/EmCEwlWbdVsRZ5zttVLhreB7ka/L+Xkp6wxSl6TgKusOFcucF0GttkkP+JeRnYQ08bclEprP
  template:
    metadata:
      name: api-secret
      namespace: default
    type: Opaque
