apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: default
type: Opaque
stringData:
  KMA_SERVICE_KEY: "J0BFqkVUSMj7Z5ZpJ2H/vj4tZlyzBiFehh8dYiND2fK5lJ1qNoM6ZWbIBTB6q3tcFYr7q9VT53oj9qfub+T0Kg=="
