apiVersion: v1
kind: Secret
metadata:
  name: tunnel-token
  namespace: default
type: Opaque
stringData:
  token: "eyJhIjoiMGUyNWRmN2E3ODdlMWZjZDAwYzgwY2IxYTM2OTJlMWEiLCJ0IjoiOTgwMGYxZDgtYzcxOC00ZmIxLThmM2EtZTkyY2VlNzg0ODMyIiwicyI6IlltVmxZVGs1WXpJdFpUQTVPQzAwTnpRNExXSTVNVEV0T1RRNU5tVmtOVFUzTWpVeiJ9"